
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    
    /// <summary>
    /// Connection information to the default port.
    /// </summary>
    [Serializable]
    public class ActiveConnectionInfo
    {
        [SerializeField]
        [JsonProperty("host")]
        public string Host { get; set; } = default!;
        
        [SerializeField]
        [JsonProperty("port")]
        public double Port { get; set; } = default!;
        
        /// <summary>
        /// Unique identifier to a game session or match. Use either a system generated ID or pass in your own.
        /// </summary>
        [SerializeField]
        [JsonProperty("roomId")]
        public string RoomId { get; set; } = default!;
        
        [SerializeField]
        [JsonProperty("status")]
        public ActiveConnectionInfoStatus Status { get; set; } = default!;
        
        /// <summary>
        /// Transport type specifies the underlying communication protocol to the exposed port.
        /// </summary>
        [SerializeField]
        [JsonProperty("transportType")]
        public TransportType TransportType { get; set; } = default!;
        
    }
    
}