
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class ApplicationWithLatestDeploymentAndBuildDeprecatedServiceConfig
    {

        /// <summary>
        /// The headroom configuration for each region.<br/>
        /// 
        /// <remarks>
        /// EXPERIMENTAL - this feature is in closed beta.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("staticProcessAllocation")]
        public List<StaticProcessAllocationConfig> StaticProcessAllocation { get; set; } = default!;
    }
}