
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class AutoscalerConfig
    {

        /// <summary>
        /// If vCPU utilization rate is above this threshold percentage, the autoscaler will scale up.<br/>
        /// 
        /// <remarks>
        /// If set to 100 this disables preemptive autoscaling (i.e. nodes will only scale up when you<br/>
        /// run out of capacity and request more resources).
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("scaleUpThreshold")]
        public int ScaleUpThreshold { get; set; } = default!;
    }
}