
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using HathoraCloud.Utils;
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.Numerics;
    using System;
    using UnityEngine;
    

    public class CreateUserInviteScopesType
    {
        private CreateUserInviteScopesType(string value) { Value = value; }

        public string Value { get; private set; }
        public static CreateUserInviteScopesType UserRole { get { return new CreateUserInviteScopesType("UserRole"); } }
        public static CreateUserInviteScopesType ArrayOfScope { get { return new CreateUserInviteScopesType("arrayOfScope"); } }
        public static CreateUserInviteScopesType Null { get { return new CreateUserInviteScopesType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CreateUserInviteScopesType v) { return v.Value; }
        public static CreateUserInviteScopesType FromString(string v) {
            switch(v) {
                case "UserRole": return UserRole;
                case "arrayOfScope": return ArrayOfScope;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for CreateUserInviteScopesType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CreateUserInviteScopesType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    
/// <summary>
/// If not defined, the user has Admin access.
/// </summary>
    [JsonConverter(typeof(CreateUserInviteScopes.CreateUserInviteScopesConverter))]
    public class CreateUserInviteScopes {
        public CreateUserInviteScopes(CreateUserInviteScopesType type) {
            Type = type;
        }
        public UserRole? UserRole { get; set; } 
        public List<Scope>? ArrayOfScope { get; set; } 

        public CreateUserInviteScopesType Type {get; set; }


        public static CreateUserInviteScopes CreateUserRole(UserRole userRole) {
            CreateUserInviteScopesType typ = CreateUserInviteScopesType.UserRole;

            CreateUserInviteScopes res = new CreateUserInviteScopes(typ);
            res.UserRole = userRole;
            return res;
        }

        public static CreateUserInviteScopes CreateArrayOfScope(List<Scope> arrayOfScope) {
            CreateUserInviteScopesType typ = CreateUserInviteScopesType.ArrayOfScope;

            CreateUserInviteScopes res = new CreateUserInviteScopes(typ);
            res.ArrayOfScope = arrayOfScope;
            return res;
        }

        public static CreateUserInviteScopes CreateNull() {
            CreateUserInviteScopesType typ = CreateUserInviteScopesType.Null;
            return new CreateUserInviteScopes(typ);
        }

        public class CreateUserInviteScopesConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(CreateUserInviteScopes);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    UserRole? userRole = JsonConvert.DeserializeObject<UserRole>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonDeserializers(typeof(UserRole))});
                    return new CreateUserInviteScopes(CreateUserInviteScopesType.UserRole) {
                        UserRole = userRole
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    List<Scope>? arrayOfScope = JsonConvert.DeserializeObject<List<Scope>>(json, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Error, Converters = Utilities.GetJsonDeserializers(typeof(List<Scope>))});
                    return new CreateUserInviteScopes(CreateUserInviteScopesType.ArrayOfScope) {
                        ArrayOfScope = arrayOfScope
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                CreateUserInviteScopes res = (CreateUserInviteScopes)value;
                if (CreateUserInviteScopesType.FromString(res.Type).Equals(CreateUserInviteScopesType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.UserRole != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.UserRole));
                    return;
                }
                if (res.ArrayOfScope != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfScope));
                    return;
                }

            }
        }

    }

}