
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// A fleet is a collection of nodes across your regions that can scale up and down based on demand.
    /// </summary>
    [Serializable]
    public class Fleet
    {

        [SerializeField]
        [JsonProperty("autoscalerConfig")]
        public AutoscalerConfig? AutoscalerConfig { get; set; }

        /// <summary>
        /// The id of the fleet.
        /// </summary>
        [SerializeField]
        [JsonProperty("fleetId")]
        public string FleetId { get; set; } = default!;

        /// <summary>
        /// Readable name for a fleet. Must be unique within an organization.
        /// </summary>
        [SerializeField]
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [SerializeField]
        [JsonProperty("nodeShape")]
        public NodeShape NodeShape { get; set; } = default!;

        /// <summary>
        /// System generated unique identifier for an organization. Not guaranteed to have a specific format.
        /// </summary>
        [SerializeField]
        [JsonProperty("orgId")]
        public string OrgId { get; set; } = default!;
    }
}