
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class FleetMetricsData
    {

        [SerializeField]
        [JsonProperty("provisionedBareMetal")]
        public List<MetricValue>? ProvisionedBareMetal { get; set; }

        [SerializeField]
        [JsonProperty("provisionedCloud")]
        public List<MetricValue>? ProvisionedCloud { get; set; }

        [SerializeField]
        [JsonProperty("provisionedTotal")]
        public List<MetricValue>? ProvisionedTotal { get; set; }

        [SerializeField]
        [JsonProperty("utilized")]
        public List<MetricValue>? Utilized { get; set; }
    }
}