
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class InviteStatusAccepted
    {

        [SerializeField]
        [JsonProperty("type")]
        public Type Type { get; set; } = default!;

        /// <summary>
        /// System generated unique identifier for a user. Not guaranteed to have a specific format.
        /// </summary>
        [SerializeField]
        [JsonProperty("userId")]
        public string UserId { get; set; } = default!;
    }
}