
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class LoadBalancerConfig
    {

        /// <summary>
        /// Whether load balancing is enabled for this application.
        /// </summary>
        [SerializeField]
        [JsonProperty("enabled")]
        public bool Enabled { get; set; } = default!;
    }
}