
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The name of the metric.<br/>
    /// 
    /// <remarks>
    /// Allowed values:<br/>
    /// `concurrent-requests`: Tracks the number of concurrent requests that a single Process handles.
    /// </remarks>
    /// </summary>
    public enum MetricName
    {
        [JsonProperty("concurrent-requests")]
        ConcurrentRequests,
    }

    public static class MetricNameExtension
    {
        public static string Value(this MetricName value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static MetricName ToEnum(this string value)
        {
            foreach(var field in typeof(MetricName).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (MetricName)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum MetricName");
        }
    }

}