
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    public enum NodeShape
    {
        [JsonProperty("cpu-4-8")]
        Cpu48,
        [JsonProperty("cpu-8-16")]
        Cpu816,
        [JsonProperty("cpu-16-32")]
        Cpu1632,
        [JsonProperty("cpu-32-64")]
        Cpu3264,
        [JsonProperty("cpu-64-128")]
        Cpu64128,
        [JsonProperty("cpu-4-16")]
        Cpu416,
        [JsonProperty("cpu-8-32")]
        Cpu832,
        [JsonProperty("cpu-16-64")]
        Cpu1664,
        [JsonProperty("cpu-32-128")]
        Cpu32128,
        [JsonProperty("gpu-l4-1-4-16")]
        GpuL41416,
        [JsonProperty("gpu-l4-1-12-48")]
        GpuL411248,
        [JsonProperty("gpu-l4-2-24-96")]
        GpuL422496,
        [JsonProperty("gpu-l4-4-48-192")]
        GpuL4448192,
        [JsonProperty("gpu-l4-8-96-384")]
        GpuL4896384,
        [JsonProperty("gpu-h100-1-26-234")]
        GpuH100126234,
        [JsonProperty("gpu-h100-2-52-468")]
        GpuH100252468,
        [JsonProperty("gpu-h100-4-104-936")]
        GpuH1004104936,
        [JsonProperty("gpu-h100-8-208-1872")]
        GpuH10082081872,
    }

    public static class NodeShapeExtension
    {
        public static string Value(this NodeShape value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static NodeShape ToEnum(this string value)
        {
            foreach(var field in typeof(NodeShape).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (NodeShape)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum NodeShape");
        }
    }

}