
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    public enum NodeFamilyId
    {
        [JsonProperty("family-amd64-1-2")]
        FamilyAmd6412,
        [JsonProperty("family-amd64-1-4")]
        FamilyAmd6414,
        [JsonProperty("family-l4-1-4")]
        FamilyL414,
        [JsonProperty("family-l4-1-12")]
        FamilyL4112,
        [JsonProperty("family-h100pcie")]
        FamilyH100pcie,
        [JsonProperty("family-h100sxm5")]
        FamilyH100sxm5,
        [JsonProperty("family-h200sxm5")]
        FamilyH200sxm5,
        [JsonProperty("family-b200sxm5")]
        FamilyB200sxm5,
    }

    public static class NodeFamilyIdExtension
    {
        public static string Value(this NodeFamilyId value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static NodeFamilyId ToEnum(this string value)
        {
            foreach(var field in typeof(NodeFamilyId).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (NodeFamilyId)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum NodeFamilyId");
        }
    }

}