
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class NodeShapeV2
    {

        [SerializeField]
        [JsonProperty("familyId")]
        public NodeFamilyId FamilyId { get; set; } = default!;

        /// <summary>
        /// A human readable name for this node&apos;s family.
        /// </summary>
        [SerializeField]
        [JsonProperty("familyName")]
        public string FamilyName { get; set; } = default!;

        /// <summary>
        /// The minimum number of CPUs that will be in any node with this shape.<br/>
        /// 
        /// <remarks>
        /// Note: this number may change as new providers are added.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("minCPU")]
        public double MinCPU { get; set; } = default!;

        /// <summary>
        /// The minimum number of GPUs that will be in any node with this shape.<br/>
        /// 
        /// <remarks>
        /// Note: this number may change as new providers are added.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("minGPU")]
        public double MinGPU { get; set; } = default!;

        /// <summary>
        /// The minimum MB of memory that will be in any node with this shape.<br/>
        /// 
        /// <remarks>
        /// Note: this number may change as new providers are added.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("minMemoryMB")]
        public double MinMemoryMB { get; set; } = default!;

        /// <summary>
        /// A human readable name for this node shape.
        /// </summary>
        [SerializeField]
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [SerializeField]
        [JsonProperty("nodeShapeId")]
        public NodeShapeId NodeShapeId { get; set; } = default!;
    }
}