
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    public enum NodeShapeId
    {
        [JsonProperty("shape-amd64-4-8")]
        ShapeAmd6448,
        [JsonProperty("shape-amd64-8-16")]
        ShapeAmd64816,
        [JsonProperty("shape-amd64-16-32")]
        ShapeAmd641632,
        [JsonProperty("shape-amd64-32-64")]
        ShapeAmd643264,
        [JsonProperty("shape-amd64-64-128")]
        ShapeAmd6464128,
        [JsonProperty("shape-amd64-4-16")]
        ShapeAmd64416,
        [JsonProperty("shape-amd64-8-32")]
        ShapeAmd64832,
        [JsonProperty("shape-amd64-16-64")]
        ShapeAmd641664,
        [JsonProperty("shape-amd64-32-128")]
        ShapeAmd6432128,
        [JsonProperty("shape-l4-1-4")]
        ShapeL414,
        [JsonProperty("shape-l4-1")]
        ShapeL41,
        [JsonProperty("shape-l4-2")]
        ShapeL42,
        [JsonProperty("shape-l4-4")]
        ShapeL44,
        [JsonProperty("shape-l4-8")]
        ShapeL48,
        [JsonProperty("shape-h100pcie-1")]
        ShapeH100pcie1,
        [JsonProperty("shape-h100pcie-2")]
        ShapeH100pcie2,
        [JsonProperty("shape-h100pcie-4")]
        ShapeH100pcie4,
        [JsonProperty("shape-h100pcie-8")]
        ShapeH100pcie8,
        [JsonProperty("shape-h100sxm5-1")]
        ShapeH100sxm51,
        [JsonProperty("shape-h100sxm5-8")]
        ShapeH100sxm58,
        [JsonProperty("shape-h200sxm5-1")]
        ShapeH200sxm51,
        [JsonProperty("shape-h200sxm5-8")]
        ShapeH200sxm58,
    }

    public static class NodeShapeIdExtension
    {
        public static string Value(this NodeShapeId value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static NodeShapeId ToEnum(this string value)
        {
            foreach(var field in typeof(NodeShapeId).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (NodeShapeId)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum NodeShapeId");
        }
    }

}