
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    public enum NodeV1Status
    {
        [JsonProperty("running")]
        Running,
        [JsonProperty("draining")]
        Draining,
        [JsonProperty("stopped")]
        Stopped,
    }

    public static class NodeV1StatusExtension
    {
        public static string Value(this NodeV1Status value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static NodeV1Status ToEnum(this string value)
        {
            foreach(var field in typeof(NodeV1Status).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (NodeV1Status)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum NodeV1Status");
        }
    }

}