
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class Organization
    {

        /// <summary>
        /// The maximum number of concurrent processes that can be run by the organization<br/>
        /// 
        /// <remarks>
        /// If undefined, the organization has no limit.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("concurrentProcessVcpusLimit")]
        public double? ConcurrentProcessVcpusLimit { get; set; }

        /// <summary>
        /// The features enabled for this org and user.
        /// </summary>
        [SerializeField]
        [JsonProperty("enabledFeatureFlags")]
        public List<string>? EnabledFeatureFlags { get; set; }

        [SerializeField]
        [JsonProperty("isSingleTenant")]
        public bool IsSingleTenant { get; set; } = default!;

        /// <summary>
        /// The retention period for process logs in hours<br/>
        /// 
        /// <remarks>
        /// If undefined, the default is 72h
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("logRetentionPeriodHours")]
        public int? LogRetentionPeriodHours { get; set; }

        /// <summary>
        /// The maximum number of cloud nodes that can be set as baseline<br/>
        /// 
        /// <remarks>
        /// If undefined, the default is 10
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("maxCloudBaseline")]
        public int? MaxCloudBaseline { get; set; }

        /// <summary>
        /// The maximum number of inbound connections that can be made to a process<br/>
        /// 
        /// <remarks>
        /// If undefined, the default is 1024 connections
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("maxProcessConnections")]
        public double? MaxProcessConnections { get; set; }

        /// <summary>
        /// The maximum memory in MB that can be used by any process in this org.
        /// </summary>
        [SerializeField]
        [JsonProperty("maxRequestedMemoryMB")]
        public double MaxRequestedMemoryMB { get; set; } = default!;

        /// <summary>
        /// The maximum number of monthly process vcpu hours that can be run by the organization<br/>
        /// 
        /// <remarks>
        /// If undefined, the organization has no limit.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("monthlyProcessVcpuHoursLimit")]
        public double? MonthlyProcessVcpuHoursLimit { get; set; }

        /// <summary>
        /// The name of an organization.
        /// </summary>
        [SerializeField]
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// System generated unique identifier for an organization. Not guaranteed to have a specific format.
        /// </summary>
        [SerializeField]
        [JsonProperty("orgId")]
        public string OrgId { get; set; } = default!;

        /// <summary>
        /// The maximum lifespan in hours of a pod.
        /// </summary>
        [SerializeField]
        [JsonProperty("podMaxLifespanHrs")]
        public double? PodMaxLifespanHrs { get; set; }

        /// <summary>
        /// The scopes the user who loaded this has on this org.
        /// </summary>
        [SerializeField]
        [JsonProperty("scopes")]
        public List<Scope> Scopes { get; set; } = default!;

        [SerializeField]
        [JsonProperty("stripeCustomerId")]
        public string StripeCustomerId { get; set; } = default!;
    }
}