
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Make all properties in T optional
    /// </summary>
    [Serializable]
    public class PartialAppConfigWithServiceConfig
    {

        [SerializeField]
        [JsonProperty("appName")]
        public string? AppName { get; set; }

        /// <summary>
        /// Configure <a href="https://hathora.dev/docs/backend-integrations/lobbies-and-matchmaking/auth-service">player authentication</a> for your application. Use Hathora&apos;s built-in auth providers or use your own <a href="https://hathora.dev/docs/lobbies-and-matchmaking/auth-service#custom-auth-provider">custom authentication</a>.
        /// </summary>
        [SerializeField]
        [JsonProperty("authConfiguration")]
        public AuthConfiguration? AuthConfiguration { get; set; }

        [SerializeField]
        [JsonProperty("serviceConfig")]
        public ServiceConfigWrite? ServiceConfig { get; set; }
    }
}