
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Make all properties in T optional
    /// </summary>
    [Serializable]
    public class PartialRecordRegionFleetErrorState
    {

        [SerializeField]
        [JsonProperty("Chicago")]
        public FleetErrorState? Chicago { get; set; }

        [SerializeField]
        [JsonProperty("Dallas")]
        public FleetErrorState? Dallas { get; set; }

        [SerializeField]
        [JsonProperty("Dubai")]
        public FleetErrorState? Dubai { get; set; }

        [SerializeField]
        [JsonProperty("Frankfurt")]
        public FleetErrorState? Frankfurt { get; set; }

        [SerializeField]
        [JsonProperty("Johannesburg")]
        public FleetErrorState? Johannesburg { get; set; }

        [SerializeField]
        [JsonProperty("London")]
        public FleetErrorState? London { get; set; }

        [SerializeField]
        [JsonProperty("Los_Angeles")]
        public FleetErrorState? LosAngeles { get; set; }

        [SerializeField]
        [JsonProperty("Mumbai")]
        public FleetErrorState? Mumbai { get; set; }

        [SerializeField]
        [JsonProperty("Sao_Paulo")]
        public FleetErrorState? SaoPaulo { get; set; }

        [SerializeField]
        [JsonProperty("Seattle")]
        public FleetErrorState? Seattle { get; set; }

        [SerializeField]
        [JsonProperty("Singapore")]
        public FleetErrorState? Singapore { get; set; }

        [SerializeField]
        [JsonProperty("Sydney")]
        public FleetErrorState? Sydney { get; set; }

        [SerializeField]
        [JsonProperty("Tokyo")]
        public FleetErrorState? Tokyo { get; set; }

        [SerializeField]
        [JsonProperty("Washington_DC")]
        public FleetErrorState? WashingtonDC { get; set; }
    }
}