
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// The configuration for the Process Autoscaler for this application.<br/>
    /// 
    /// <remarks>
    /// Autoscaling must be enabled on a per-region basis.<br/>
    /// EXPERIMENTAL - This feature is in closed beta.
    /// </remarks>
    /// </summary>
    [Serializable]
    public class ProcessAutoscalerConfig
    {

        [SerializeField]
        [JsonProperty("targetMetric")]
        public AutoscalerTargetMetric TargetMetric { get; set; } = default!;
    }
}