
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class StaticProcessAllocationConfigWrite
    {

        /// <summary>
        /// Whether autoscaling is enabled in this region. When enabled, `targetProcesses` is managed by the Process Autoscaler<br/>
        /// 
        /// <remarks>
        /// in accordance with the `processAutoscalerConfig` field set on the application&apos;s `serviceConfig`.<br/>
        /// There MUST be a `processAutoscalerConfig` for the application in order to enable autoscaling.<br/>
        /// EXPERIMENTAL - this feature is in closed beta.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("autoscalingEnabled")]
        public bool? AutoscalingEnabled { get; set; }

        /// <summary>
        /// The maximum number of running processes.<br/>
        /// 
        /// <remarks>
        /// When maxProcesses is null, will be set to a system-defined maximum value.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("maxProcesses", NullValueHandling = NullValueHandling.Include)]
        public int? MaxProcesses { get; set; } = default!;

        /// <summary>
        /// The minimum number of running processes.<br/>
        /// 
        /// <remarks>
        /// Invariant: 0 &lt;= minProcesses &lt; targetProcesses
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("minProcesses")]
        public int MinProcesses { get; set; } = default!;

        [SerializeField]
        [JsonProperty("region")]
        public Region Region { get; set; } = default!;

        /// <summary>
        /// The target number of running processes.<br/>
        /// 
        /// <remarks>
        /// When using process autoscaling, targetProcesses MUST NOT be set in this object.<br/>
        /// targetProcesses will be managed by the ProcessAutoscaler
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("targetProcesses")]
        public int? TargetProcesses { get; set; }
    }
}