
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class UpdateUserInvite
    {

        /// <summary>
        /// Scopes can only be removed or added if a user has those scopes.
        /// </summary>
        [SerializeField]
        [JsonProperty("scopes")]
        public UpdateUserInviteScopes Scopes { get; set; } = default!;

        /// <summary>
        /// A user&apos;s email.
        /// </summary>
        [SerializeField]
        [JsonProperty("userEmail")]
        public string UserEmail { get; set; } = default!;
    }
}