
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class UsageLimits
    {

        [SerializeField]
        [JsonProperty("concurrentProcessVcpus7DayMax")]
        public double ConcurrentProcessVcpus7DayMax { get; set; } = default!;

        [SerializeField]
        [JsonProperty("concurrentProcessVcpusLimit")]
        public double? ConcurrentProcessVcpusLimit { get; set; }

        [SerializeField]
        [JsonProperty("monthlyProcessVcpuHoursConsumed")]
        public double MonthlyProcessVcpuHoursConsumed { get; set; } = default!;

        [SerializeField]
        [JsonProperty("monthlyProcessVcpuHoursLimit")]
        public double? MonthlyProcessVcpuHoursLimit { get; set; }
    }
}