
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class UsageLimits
    {

        /// <summary>
        /// The maximum number of concurrent processes that have been run by the organization in the last 7 days.
        /// </summary>
        [SerializeField]
        [JsonProperty("concurrentProcessVcpus7DayMax")]
        public double ConcurrentProcessVcpus7DayMax { get; set; } = default!;

        /// <summary>
        /// The maximum number of concurrent processes that can be run by the organization<br/>
        /// 
        /// <remarks>
        /// If undefined, the organization has no limit.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("concurrentProcessVcpusLimit")]
        public double? ConcurrentProcessVcpusLimit { get; set; }

        /// <summary>
        /// The number of vCPU hours used up by the organization in the current month.
        /// </summary>
        [SerializeField]
        [JsonProperty("monthlyProcessVcpuHoursConsumed")]
        public double MonthlyProcessVcpuHoursConsumed { get; set; } = default!;

        /// <summary>
        /// The maximum number of monthly process vcpu hours that can be run by the organization<br/>
        /// 
        /// <remarks>
        /// If undefined, the organization has no limit.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("monthlyProcessVcpuHoursLimit")]
        public double? MonthlyProcessVcpuHoursLimit { get; set; }
    }
}