
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Hathora.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    
    [Serializable]
    public class AppConfig
    {
        /// <summary>
        /// Readable name for an application. Must be unique within an organization.
        /// </summary>
        [SerializeField]
        [JsonProperty("appName")]
        public string AppName { get; set; } = default!;
        
        /// <summary>
        /// Configure [player authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service) for your application. Use Hathora's built-in auth providers or use your own [custom authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service#custom-auth-provider).
        /// </summary>
        [SerializeField]
        [JsonProperty("authConfiguration")]
        public AuthConfiguration AuthConfiguration { get; set; } = default!;
        
    }
    
}