workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://hathora.dev/swagger.json
targets:
    cloud-sdk-unity:
        target: unity
        source: my-source
        output: .
