workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://hathora.dev/swagger.json
        overlays:
            - location: overlay.yaml
targets:
    cloud-sdk-unity:
        target: unity
        source: my-source
        output: .
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/hathora/hathora/code-samples-unity-cloud-sdk-unity
