
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Operations
{
    using HathoraCloud.Models.Shared;
    using System;
    using UnityEngine.Networking;
    using UnityEngine;
    
    [Serializable]
    public class CreateLocalLobbyResponse: IDisposable
    {

        /// <summary>
        /// HTTP response content type for this operation
        /// </summary>
        [SerializeField]
        public string? ContentType { get; set; } = default!;
        

        [SerializeField]
        public string? CreateLocalLobby400ApplicationJSONString { get; set; }
        

        [SerializeField]
        public string? CreateLocalLobby401ApplicationJSONString { get; set; }
        

        [SerializeField]
        public string? CreateLocalLobby404ApplicationJSONString { get; set; }
        

        [SerializeField]
        public string? CreateLocalLobby422ApplicationJSONString { get; set; }
        

        [SerializeField]
        public string? CreateLocalLobby429ApplicationJSONString { get; set; }
        

        [SerializeField]
        public string? CreateLocalLobby500ApplicationJSONString { get; set; }
        

        [SerializeField]
        public Lobby? Lobby { get; set; }
        

        /// <summary>
        /// HTTP response status code for this operation
        /// </summary>
        [SerializeField]
        public int StatusCode { get; set; } = default!;
        

        /// <summary>
        /// Raw HTTP response; suitable for custom response parsing
        /// </summary>
        [SerializeField]
        public UnityWebRequest? RawResponse { get; set; }
        
        public void Dispose() {
            if (RawResponse != null) {
                RawResponse.Dispose();
            }
        }
    }
}