
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Operations
{
    using HathoraCloud.Models.Shared;
    using HathoraCloud.Utils;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class GetFleetRegionMetricsRequest
    {

        [SerializeField]
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=end")]
        public double? End { get; set; }

        [SerializeField]
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=fleetId")]
        public string FleetId { get; set; } = default!;

        /// <summary>
        /// Available metrics to query over time.
        /// </summary>
        [SerializeField]
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=metrics")]
        public List<FleetMetricName>? Metrics { get; set; }

        [SerializeField]
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=orgId")]
        public string? OrgId { get; set; }

        [SerializeField]
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=region")]
        public Region Region { get; set; } = default!;

        /// <summary>
        /// Unix timestamp. Default is -1 hour from `end`.
        /// </summary>
        [SerializeField]
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=start")]
        public double? Start { get; set; }

        [SerializeField]
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=step")]
        public int? Step { get; set; }
    }
}